man: Molex
mpn: 85502
orientation: H
category: 3
depth: 18.1
center: [0, -0.12]
pad:
  type: SMT
  pitch: [1.27, 0]
  size: [.76, 6.35]
  position: 10.375
mount:
  type: SMT
  number: MP
  size: [5.15, 2.8]
  position: 7.88
templates:
  4: &4
    positions: 4
    width: 11.18
    mount:
      separation: 12.09
  6: &6
    positions: 6
    width: 13.21
    mount:
      separation: 14.12
  8: &8
    positions: 8
    width: 15.24
    mount:
      separation: 16.15
variants:
  5005:
    <<: *4
    connected: 4
  5006:
    <<: *6
    connected: 4
  5007:
    <<: *6
    connected: 6
  5008:
    <<: *8
    connected: 8
