man: Molex
mpn: 95540
variant: 688x
positions: 8
connected: 8
orientation: V
category: 3
width: 15.24
depth: 18.10
center: [0, -0.445]
pad:
  type: SMT
  pitch: [1.27, 0]
  size: [.76, 6.35]
  position: 10.225
mount:
  type: NPTH
  drill: 3.25
  position: 7.88
  separation: 11.43
side:
  - type: SMT
    size: [2.54, 2.94]
    number: SH
    position: [-2.75, 3.05]
